trigger:
- master

pool:
  vmImage: azrelease

stages:
- stage: Deploy
  displayName: 'Deploy Stage'
  jobs:
  - job: DeployJob
    displayName: 'Deploy Job'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'Install and Build'

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          az login --service-principal -u $(servicePrincipalId) -p $(servicePrincipalKey) --tenant $(tenantId)
      displayName: 'Login Azure'

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          ids=$(az webapp list --query '[0].id' -o tsv)
          repo_url=https://github.com/bha1212002/food-app-project.git
          az webapp deployment source config --branch master --manual-integration --repo-url $repo_url --ids $ids
          az webapp deployment source sync --ids $ids
      displayName: 'Push to Azure'
